### ISSUE TITLE
RingBuffer::as_slice is broken

### ISSUE THREAD

**Issue by tov** [sarahlim/wasm-trace#23]
```rust
    pub fn as_slice(&self) -> &[T] {
        let (front, back) = self.data.as_slices();
        assert!(back.is_empty(), "elements are only inserted at the back");
        front
    }
```

Once you start wrapping around the buffer, this is going to assert false. Here's a test case that will panic, I believe:

```rust
#[test]
fn as_slice_wrap_around() {
    let buf = RingBuffer::<i32>::new(3);
    buf.enqueue(0);
    buf.enqueue(1);
    buf.enqueue(2);
    buf.enqueue(3);
    // At this point, the buffer contains [3, 1, 2], so front is &[1, 2]
    // and back is &[3].
    buf.as_slice();
}
```

**Comment by sarahlim** [comment]
Thanks! We should handle this after #20, which will involve rewriting the `RingBuffer` to replace the`VecDeque`.

**Comment by tov** [comment]
Is there a particular reason you want it not to allocate? Does the buffer need to be pinned?

**Comment by sarahlim** [comment]
>  [I am so sorry to have take a year to answer.](https://github.com/flexible-collision-library/fcl/issues/122#issuecomment-323139702)

I think the current implementation is actually correct, though it's a bit subtle as to why (and my naming could probably improve). The test case you provided passes, and moreover after
```rust
buf.enqueue(0);
buf.enqueue(1);
buf.enqueue(2);
buf.enqueue(3);
```
the contents of the `VecDeque` are
```
([1, 2, 3], [])
```
for `front` and `back`, respectively.

The [example](https://doc.rust-lang.org/std/collections/struct.VecDeque.html#method.as_slices) in the docs for `as_slices()` indicates why:

- If only `push_back()` is called, the `VecDeque` only appends to the `front` vector.
- If `push_front()` is subsequently called, the `VecDeque` swaps `front` and `back` and appends to `front`.
- Since our implementation only ever calls `push_back()` (and never `push_front()`), only the internal `front` vector is ever used.
